version: '3.8'

services:
  mysql:
    image: mysql:8.0.32  # Ensure this matches your expected MySQL version
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    networks:
      - my_network

  springboot-app:
    image: wassimbecheikh/orange:latest
    container_name: springboot_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/my_database?autoReconnect=true&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_password
      SERVER_PORT: "8083"
      SPRING_JPA_SHOW_SQL: "true"  # Ensure this is a string
    ports:
      - "8083:8083"
    depends_on:
      - mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge